---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: calendar
  name: calendar
spec:
  ports:
    - name: "5005"
      port: 5005
      targetPort: 5005
  selector:
    io.kompose.service: calendar

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: frontend

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: search
  name: search
spec:
  ports:
    - name: "5010"
      port: 5010
      targetPort: 5010
  selector:
    io.kompose.service: search

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: task-service
  name: task-service
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5002
  selector:
    io.kompose.service: task-service

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: user-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: calendar
  name: calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: calendar
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: calendar
    spec:
      containers:
        - env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PASSWORD
              value: password
            - name: RABBITMQ_USER
              value: admin
          image: yevheniisekhin/calendar
          name: calendar
          ports:
            - containerPort: 5005
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PASSWORD
              value: password
            - name: RABBITMQ_USER
              value: admin
          image: yevheniisekhin/frontend
          name: frontend
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: search
  name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: search
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: search
    spec:
      containers:
        - env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PASSWORD
              value: password
            - name: RABBITMQ_USER
              value: admin
          image: yevheniisekhin/search
          name: search
          ports:
            - containerPort: 5010
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: task-service
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: task-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: task-service
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: task-db
            - name: DB_NAME
              value: tasks
            - name: DB_PASS
              value: A7noth56therUser
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: task_admin
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PASSWORD
              value: password
            - name: RABBITMQ_USER
              value: admin
          image: yevheniisekhin/task-service
          name: task-service
          ports:
            - containerPort: 5002
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o deployment.yaml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yaml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: user-db
            - name: DB_NAME
              value: users
            - name: DB_PASS
              value: eighty9@doublet
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: user_admin
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PASSWORD
              value: password
            - name: RABBITMQ_USER
              value: admin
          image: yevheniisekhin/user-service
          name: user-service
          ports:
            - containerPort: 5001
              protocol: TCP
      restartPolicy: Always
