services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
  
  search:
    build:
      context: ./search
    ports:
      - "5010:5010"
  
  calendar:
    build:
      context: ./calendar
    ports:
      - "5005:5005"
    
  user-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: eighty9@doublet
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    depends_on:
      - user-db
    environment:
      PYTHONUNBUFFERED: 1  # For auto flush
      DB_HOST: user-db
      DB_PORT: 5432
      DB_NAME: users
      DB_USER: user_admin
      DB_PASS: eighty9@doublet
    ports:
      - "5001:5001"
  
  task-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: task_admin
      POSTGRES_PASSWORD: A7noth56therUser
    volumes:
      - task_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Outer 5433 port

  task-service:
    build:
      context: .
      dockerfile: task-service/Dockerfile
    depends_on:
      - task-db
    environment:
      PYTHONUNBUFFERED: 1  # for auto flush
      DB_HOST: task-db
      DB_PORT: 5432
      DB_NAME: tasks
      DB_USER: task_admin
      DB_PASS: A7noth56therUser
    ports:
      - "5002:5002"

volumes:
  user_postgres_data:
  task_postgres_data:
