---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
  selector:
    io.kompose.service: rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: task-db
  name: task-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: task-db

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: user-db
  name: user-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: user-db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq
  template:
    metadata:
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
        - args:
            - rabbitmq-server
            - -frame_max
            - "268435456"
          env:
            - name: RABBITMQ_DEFAULT_PASS
              value: password
            - name: RABBITMQ_DEFAULT_USER
              value: admin
            - name: RABBITMQ_ERLANG_COOKIE
              value: supersecretcookie
          image: rabbitmq:3-management
          readinessProbe:
            exec:
              command:
                - rabbitmqctl
                - status
            failureThreshold: 20
            periodSeconds: 2
            timeoutSeconds: 10
          name: rabbitmq
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: task-db
  name: task-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: task-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: task-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: tasks
            - name: POSTGRES_PASSWORD
              value: A7noth56therUser
            - name: POSTGRES_USER
              value: task_admin
          image: postgres:17
          readinessProbe:
            exec:
              command:
                - pg_isready
                - "-U"
                - "task_admin"
                - "-d"
                - "tasks"
            failureThreshold: 20
            periodSeconds: 2
            timeoutSeconds: 10
          name: task-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: task-postgres-data
      restartPolicy: Always
      volumes:
        - name: task-postgres-data
          persistentVolumeClaim:
            claimName: task-postgres-data

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: user-db
  name: user-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: user-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: users
            - name: POSTGRES_PASSWORD
              value: eighty9@doublet
            - name: POSTGRES_USER
              value: user_admin
          image: postgres:17
          readinessProbe:
            exec:
              command:
                - psql
                - "-U"
                - "user_admin"
                - "-d"
                - "users"
            failureThreshold: 20
            periodSeconds: 2
            timeoutSeconds: 10
          name: user-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: user-postgres-data
      restartPolicy: Always
      volumes:
        - name: user-postgres-data
          persistentVolumeClaim:
            claimName: user-postgres-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: task-postgres-data
  name: task-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: user-postgres-data
  name: user-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
